// Browser tests: search, carousels, PIN codes, stock holds, Help & support, account tabs, and the matching admin screens — REAL backend.
const { chromium } = require('playwright');
const CHROME = process.env.CHROME || '/home/claude/.cache/puppeteer/chrome/linux-131.0.6778.204/chrome-linux64/chrome';
const B = 'http://localhost:4000', SHOTS = process.env.SHOTS || '/tmp/shots2'; require('fs').mkdirSync(SHOTS, { recursive: true });
let pass = 0, fail = 0; const ok = (n, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS' : 'FAIL') + '  ' + n + (x ? '  — ' + x : '')); };
const api = async (path, opts = {}, token) => { const r = await fetch(B + '/api' + path, { ...opts, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(opts.headers || {}) }, body: opts.body ? JSON.stringify(opts.body) : undefined }); return { status: r.status, body: await r.json().catch(() => ({})) }; };
const BLOCK = /fonts\.(googleapis|gstatic)\.com|checkout\.razorpay\.com|gstatic\.com\/firebasejs|api\.qrserver\.com|postalpincode/;
const errs = [];
(async () => {
  await fetch(B + '/__reset-otp');
  const owner = (await api('/auth/login', { method: 'POST', body: { email: 'owner@shop.test', password: 'Passw0rd!x' } })).body.token;
  const prods = (await api('/products')).body; const rack1 = prods.find((p) => p.sku === 'CRAFTLAB-HNG-01'), rack2 = prods.find((p) => p.sku === 'CRAFTLAB-HNG-02');
  const browser = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });
  async function newPage(vp = { width: 1280, height: 900 }, authToken) {
    const ctx = await browser.newContext({ viewport: vp, deviceScaleFactor: vp.width < 500 ? 2 : 1 }); await ctx.route(BLOCK, (r) => r.abort());
    if (authToken) await ctx.addInitScript((t) => localStorage.setItem('cl_customer_token', t), authToken);
    const page = await ctx.newPage(); page.on('pageerror', (e) => errs.push(page.url().split('/').pop() + ': ' + e.message)); page.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource|ERR_/.test(m.text())) errs.push(m.text()); }); return { ctx, page };
  }
  const login = async (page, phone = '9876543210') => { await page.click('#otpLoginBtn'); await page.fill('#clOtpPhoneInput', phone); await page.check('#clOtpTerms'); await page.click('#clOtpSendBtn'); await page.waitForSelector('#clOtpStepCode', { state: 'visible' }); const code = ((await page.locator('#clOtpDevHint').textContent()).match(/\d{6}/) || [])[0]; await page.fill('#clOtpCodeInput', code); await page.waitForSelector('[data-tab=orders]', { timeout: 8000 }); };

  /* ================= SEARCH ================= */
  let { ctx, page } = await newPage();
  await page.goto(B + '/index.html'); await page.waitForSelector('#clSearchInput'); await page.fill('#clSearchInput', 'rac'); await page.waitForSelector('#clSuggest:not([hidden]) .ns-prod');
  const sg = await page.locator('#clSuggest .ns-prod').count(); ok('typing shows suggestions with image, name, SKU and price', sg === 2 && await page.locator('#clSuggest .ns-prod img').first().isVisible() && /₹2,499/.test(await page.locator('#clSuggest').textContent()) && /CRAFTLAB-HNG-0/.test(await page.locator('#clSuggest').textContent()) && await page.locator('#clSuggest mark').count() >= 1);
  await page.screenshot({ path: SHOTS + '/40-search-suggest.png' });
  await page.fill('#clSearchInput', 'craftlab-hng-02'); await page.waitForTimeout(600); ok('searching by SKU finds the right product', /Classic Row/.test(await page.locator('#clSuggest .ns-prod').first().textContent()));
  await page.keyboard.press('ArrowDown'); await Promise.all([page.waitForURL(/product\.html\?slug=/), page.keyboard.press('Enter')]); ok('keyboard: ↓ then Enter opens the highlighted product', /classic-row/.test(page.url()));
  await page.goto(B + '/index.html'); await page.fill('#clSearchInput', 'zzzzqq'); await page.waitForSelector('#clSuggest .ns-empty'); ok('no matches gives a helpful empty state', /No matches/.test(await page.locator('#clSuggest').textContent()));
  await page.fill('#clSearchInput', 'rack'); await Promise.all([page.waitForURL(/search\.html\?q=rack/), page.press('#clSearchInput', 'Enter')]); await page.waitForSelector('#results .product-card');
  ok('results page: heading, count, product cards, category filter', /Results for “rack”/.test(await page.locator('#sTitle').textContent()) && /2 products/.test(await page.locator('#sCount').textContent()) && await page.locator('#results .product-card').count() === 2 && await page.locator('#filters .fchip').count() >= 2);
  await page.selectOption('#sSort', 'price-high'); await page.waitForTimeout(700); ok('sorting is applied (and kept in the URL)', /sort=price-high/.test(page.url()));
  await page.fill('#fMin', '9999'); await page.waitForSelector('#results .empty-state'); ok('filters can empty the results gracefully', /No products found/.test(await page.locator('#results').textContent())); await page.click('#fClear'); await page.waitForSelector('#results .product-card');
  await page.screenshot({ path: SHOTS + '/41-search-results.png' }); await ctx.close();
  ({ ctx, page } = await newPage({ width: 390, height: 844 })); await page.goto(B + '/index.html'); await page.click('[data-open-search]'); await page.waitForSelector('.nav-search.open #clSearchInput'); await page.fill('#clSearchInput', 'rack'); await page.waitForSelector('#clSuggest .ns-prod');
  ok('mobile: search opens as a full-width bar with suggestions', (await page.locator('.nav-search.open .ns-form').boundingBox()).width >= 385 && !(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1))); await page.screenshot({ path: SHOTS + '/42-search-mobile.png' }); await ctx.close();

  /* ================= CAROUSELS (admin-controlled, real products) ================= */
  await api('/admin/catalog/collections/featured/products', { method: 'PUT', body: { productIds: [rack2.id, rack1.id] } }, owner);
  ({ ctx, page } = await newPage()); await page.goto(B + '/index.html'); await page.waitForSelector('.carousel-sec .product-card'); await page.waitForTimeout(500);
  const heads = await page.locator('.carousel-sec h2').allTextContents(); ok('homepage shows the enabled carousels from the database', heads.includes('Featured Products') && heads.includes('New Arrivals') && heads.includes('Best Sellers') && !heads.includes('Recommended For You'), heads.join(' | '));
  const f = page.locator('.carousel-sec[data-col=featured]'); ok('featured shows the admin’s order (Classic Row first)', /Classic Row/.test(await f.locator('.product-card').first().textContent()));
  const card = f.locator('.product-card').first(); ok('card has image, name, price, MRP, discount, wishlist and Add to cart', await card.locator('img').first().isVisible() && /₹2,499/.test(await card.textContent()) && /₹2,999/.test(await card.textContent()) && /17% OFF/.test(await card.textContent()) && await card.locator('[data-wish]').count() === 1 && await card.locator('[data-quick]').isVisible());
  ok('carousel arrows exist', await f.locator('[data-next]').count() === 1 && await f.locator('[data-prev]').count() === 1);
  await card.locator('[data-quick]').click(); await page.waitForSelector('#clCartDrawer.open .dr-item'); ok('Add to cart from the carousel opens the cart', /Classic Row/.test(await page.locator('#clCartDrawer').textContent())); await page.screenshot({ path: SHOTS + '/43-carousel-cart.png' }); await ctx.close();
  ({ ctx, page } = await newPage({ width: 390, height: 844 })); await page.goto(B + '/index.html'); await page.waitForSelector('.carousel-sec .product-card'); ok('mobile carousel scrolls sideways without breaking the page', !(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)) && (await page.locator('.carousel').first().evaluate((e) => e.scrollWidth > e.clientWidth))); await ctx.close();

  /* ================= PIN CODE CHECK + STOCK HOLD ================= */
  ({ ctx, page } = await newPage()); await page.goto(B + `/product.html?slug=${rack1.slug}`); await page.waitForSelector('#pwIn'); await page.fill('#pwIn', '12345'); await page.click('#pwBtn'); ok('an invalid PIN is rejected politely', /valid 6-digit/.test(await page.locator('#pwOut').textContent()));
  await page.fill('#pwIn', '603110'); await page.waitForSelector('#pwOut .pw-ok'); ok('a serviceable PIN shows availability, expected date and COD info', /Delivery available/.test(await page.locator('#pwOut').textContent()) && /Delivery (by|between)/.test(await page.locator('#pwOut').textContent()) && /Cash on Delivery available/.test(await page.locator('#pwOut').textContent())); await page.screenshot({ path: SHOTS + '/44-pin-widget.png' });
  ok('the checked PIN is remembered', (await page.evaluate(() => localStorage.getItem('cl_pin'))) === '603110');
  // stock hold banner
  const avail0 = (await api('/products/' + rack1.slug)).body.available; await page.click('#addToCartBtn'); await page.waitForSelector('#clCartDrawer.open .dr-item'); await page.waitForSelector('#clCartDrawer #drPin #pwIn'); ok('cart drawer also has a delivery check', await page.locator('#clCartDrawer #drPin #pwIn').count() === 1);
  await page.click('#clCartDrawer [data-checkout]'); await page.waitForSelector('#clCoModal.open'); await page.waitForTimeout(700);
  const hold = await page.locator('#coHold').textContent(); ok('entering checkout holds the stock and shows a countdown', /holding your items for \d+:\d\d/.test(hold) && /(9|10):\d\d/.test(hold), hold.trim());
  ok('the backend really reserved it (available dropped by 1)', (await api('/products/' + rack1.slug)).body.available === avail0 - 1);
  await page.screenshot({ path: SHOTS + '/45-checkout-hold.png' });
  const t1 = await page.locator('#coHold').textContent(); await page.waitForTimeout(2200); ok('the countdown ticks down', (await page.locator('#coHold').textContent()) !== t1);
  await page.click('[data-co="close"]'); await page.waitForTimeout(900); ok('leaving checkout gives the stock back immediately', (await api('/products/' + rack1.slug)).body.available === avail0);
  // not enough stock for a second shopper
  const rack2avail = (await api('/products/' + rack2.slug)).body.available; await api('/admin/inventory/adjust', { method: 'POST', body: { productId: rack2.id, delta: -(rack2avail - 1), reason: 'Stock counted' } }, owner);
  // shopper A puts the last unit in their cart; shopper B then enters checkout and holds it
  ({ ctx, page } = await newPage()); await page.goto(B + `/product.html?slug=${rack2.slug}`); await page.waitForSelector('#addToCartBtn:not([disabled])'); await page.click('#addToCartBtn'); await page.waitForSelector('#clCartDrawer.open .dr-item');
  const holdOther = await api('/cart', { method: 'POST' }); await api(`/cart/${holdOther.body.cartId}/items`, { method: 'POST', body: { productId: rack2.id, qty: 1 } }); const rr = await api('/checkout/reserve', { method: 'POST', body: { cartId: holdOther.body.cartId } }); ok('(setup) another shopper holds the last unit first', rr.status === 200);
  ok('the product page now shows it as unavailable to new shoppers', (await api('/products/' + rack2.slug)).body.available === 0);
  await page.evaluate(() => ShopUI.openCheckout()); await page.waitForSelector('#clCoModal.open'); await page.waitForTimeout(700);
  ok('the second shopper is told, in checkout, that it is out of stock — before paying', /out of stock|available right now|Only/i.test(await page.locator('#coHold').textContent()) && await page.locator('#coHold.bad').count() === 1, (await page.locator('#coHold').textContent()).trim().slice(0, 80)); await page.screenshot({ path: SHOTS + '/46-checkout-stock-error.png' });
  await api('/checkout/reserve/release', { method: 'POST', body: { cartId: holdOther.body.cartId } }); await api('/admin/inventory/adjust', { method: 'POST', body: { productId: rack2.id, delta: rack2avail - 1, reason: 'Stock counted' } }, owner); await ctx.close();
  // PIN registry enforced
  await api('/admin/pincodes/import', { method: 'POST', body: { csv: 'pincode,city,state,serviceable,cod,eta\n600001,Chennai,Tamil Nadu,yes,yes,2\n560001,Bengaluru,Karnataka,no,no,\n' } }, owner); await api('/admin/settings', { method: 'PUT', body: { pincodeCheckMode: 'registry' } }, owner);
  ({ ctx, page } = await newPage()); await page.goto(B + `/product.html?slug=${rack1.slug}`); await page.waitForSelector('#pwIn'); await page.fill('#pwIn', '560001'); await page.waitForSelector('#pwOut .pw-bad'); ok('an unserved PIN shows “Delivery not available”', /Delivery not available/.test(await page.locator('#pwOut').textContent()));
  await page.fill('#pwIn', '600001'); await page.waitForSelector('#pwOut .pw-ok'); ok('a listed PIN shows the PIN’s own delivery date', /Delivery by/.test(await page.locator('#pwOut').textContent()) && /Chennai/.test(await page.locator('#pwOut').textContent()));
  await page.click('#addToCartBtn'); await page.waitForSelector('#clCartDrawer.open .dr-item'); await page.click('#clCartDrawer [data-checkout]'); await page.waitForSelector('#clCoModal.open'); await page.waitForTimeout(500);
  await page.fill('#coName', 'Pin Tester'); await page.fill('#coPhone', '9123456780'); await page.fill('#coEmail', 'pin@example.com'); await page.fill('#coLine1', '1 Street'); await page.fill('#coCity', 'Bengaluru'); await page.fill('#coState', 'Karnataka'); await page.fill('#coPin', '560001'); await page.waitForTimeout(900);
  ok('checkout explains that this PIN is not served and offers no delivery option', /don’t deliver to this PIN/.test(await page.locator('#coDelivery').textContent()) && await page.locator('#coDelivery .dm-card').count() === 0);
  await page.click('[data-co="pay"]'); await page.waitForTimeout(600); ok('Pay is refused for an unserved PIN', /don’t deliver to this PIN/.test(await page.locator('#coErr').textContent()));
  await page.fill('#coPin', '600001'); await page.waitForTimeout(900); ok('a served PIN restores the options and shows the expected date', await page.locator('#coDelivery .dm-card').count() >= 1 && /Delivery by/.test(await page.locator('#coDelivery .co-eta').textContent()));
  await ctx.close(); await api('/admin/settings', { method: 'PUT', body: { pincodeCheckMode: 'off' } }, owner);

  /* ================= HELP & SUPPORT ================= */
  ({ ctx, page } = await newPage()); await page.goto(B + '/help.html?order=CL-1001#contact'); await page.waitForSelector('#tForm'); await page.waitForTimeout(700);
  ok('help centre: the six sections you listed are present', (await page.locator('.help-acc summary').allTextContents()).join('|').match(/Delivery information.*Track your order.*Return & exchange.*Promotion terms.*Terms & conditions/) !== null && await page.locator('#contact').count() === 1);
  ok('…with the number the owner configured in Settings', /wa\.me\/919876543210/.test(await page.locator('#waLink').getAttribute('href')) && /Mon–Sat 10 AM – 6 PM IST/.test(await page.locator('#hours').textContent()), await page.locator('#waLink').getAttribute('href'));
  await api('/admin/settings', { method: 'PUT', body: { supportWhatsapp: '918046800250' } }, owner); { const fresh = await newPage(); await fresh.page.goto(B + '/help.html'); await fresh.page.waitForTimeout(900); page = fresh.page; await ctx.close(); ctx = fresh.ctx; } // fresh browser = no 60-second config cache
  ok('Get in touch shows +91 80468 00250, and clicking it opens WhatsApp', (await page.locator('#waLink').textContent()).trim() === '+91 80468 00250' && /^https:\/\/wa\.me\/918046800250/.test(await page.locator('#waLink').getAttribute('href')) && /wa\.me\/918046800250/.test(await page.locator('#waBtn').getAttribute('href')));
  await api('/admin/settings', { method: 'PUT', body: { supportWhatsapp: '919876543210' } }, owner); { const fresh = await newPage(); await fresh.page.goto(B + '/help.html?order=CL-1001#contact'); await fresh.page.waitForSelector('#tForm'); await fresh.page.waitForTimeout(900); page = fresh.page; await ctx.close(); ctx = fresh.ctx; }
  ok('delivery info lists the live delivery methods; return info shows the live window', /Standard delivery/.test(await page.locator('#deliveryInfo').textContent()) && /\d+ days of delivery/.test(await page.locator('#retInfo').textContent()));
  ok('order number from the link is pre-filled', (await page.inputValue('#tOrder')) === 'CL-1001');
  await page.fill('#tName', 'Guest Gita'); await page.fill('#tEmail', 'gita@example.com'); await page.fill('#tPhone', '9876511111'); await page.fill('#tSubject', 'Where is my parcel?'); await page.fill('#tMsg', 'It has been nine days since I ordered.'); await page.click('#tBtn'); await page.waitForSelector('#tStatus strong'); const tn = await page.locator('#tStatus strong').textContent();
  ok('guest submits a request and receives a ticket number', /^TKT-\d+$/.test(tn), tn); await page.screenshot({ path: SHOTS + '/47-help-center.png', fullPage: true });
  const adminList = await api('/admin/support', {}, owner); ok('admin sees it: ticket, customer, mobile, email, order, subject, status New', adminList.body.tickets.some((t) => t.ticketNumber === tn && t.status === 'New' && t.phone === '9876511111' && t.email === 'gita@example.com' && t.orderNumber === 'CL-1001' && t.subject === 'Where is my parcel?'));
  ok('the admin bell is notified of the new request', (await api('/admin/notifications', {}, owner)).body.notifications.some((n) => n.type === 'support_request')); await ctx.close();
  // Terms checkbox on login + logged-in prefill
  ({ ctx, page } = await newPage()); await page.goto(B + '/account.html'); await page.waitForSelector('#otpLoginBtn'); await page.click('#otpLoginBtn'); await page.fill('#clOtpPhoneInput', '9876543210'); await page.click('#clOtpSendBtn');
  ok('login without ticking Terms & Conditions is refused', /accept the Terms/.test(await page.locator('#clOtpPhoneError').textContent())); await page.check('#clOtpTerms'); await page.click('#clOtpSendBtn'); await page.waitForSelector('#clOtpStepCode', { state: 'visible' });
  const code = ((await page.locator('#clOtpDevHint').textContent()).match(/\d{6}/) || [])[0]; await page.fill('#clOtpCodeInput', code); await page.waitForSelector('[data-tab=orders]');
  ok('account tabs: My Details, Order History, Wishlist, Address Book, Returns, Support… and Sign out', (await page.locator('.acct-tabs button').allTextContents()).join('|').replace(/\s+/g, ' ').match(/My Details\|Order History\|Wishlist\|Rewards\|Address Book\|Returns\|Support\|Updates\|Sign out/) !== null);
  await page.goto(B + '/help.html?order=CL-1004#contact'); await page.waitForTimeout(900); ok('logged in: name, mobile and email are filled from the account (read-only)', (await page.inputValue('#tName')) !== '' && /9876543210/.test(await page.inputValue('#tPhone')) && await page.locator('#tPhone').getAttribute('readonly') !== null && (await page.inputValue('#tOrder')) === 'CL-1004');
  await page.fill('#tSubject', 'Question about my delivered order'); await page.fill('#tMsg', 'The finish is lovely — how do I care for it?'); await page.click('#tBtn'); await page.waitForSelector('#tStatus strong'); const tn2 = await page.locator('#tStatus strong').textContent(); ok('logged-in customer’s ticket is linked to their account', (await api('/admin/support', {}, owner)).body.tickets.find((t) => t.ticketNumber === tn2)?.customerId != null);
  const tid = (await api('/admin/support', {}, owner)).body.tickets.find((t) => t.ticketNumber === tn2).id; await api(`/admin/support/${tid}/reply`, { method: 'POST', body: { text: 'Wipe with a dry cloth — avoid water.' } }, owner);
  await page.goto(B + '/account.html?tab=support'); await page.waitForSelector('.tkt'); ok('Support tab shows the ticket and our reply; the customer can reply', /Wipe with a dry cloth/.test(await page.locator('.tkt').first().textContent()));
  await page.fill('.tkt form input', 'Thank you!'); await page.click('.tkt form button'); await page.waitForTimeout(900); ok('customer reply is saved', /Thank you!/.test(await page.locator('.tkt').first().textContent()));
  await page.goto(B + '/account.html?tab=returns'); await page.waitForTimeout(900); ok('Returns tab explains the window and lists returns', /days of delivery/.test(await page.locator('#tabBody').textContent()));
  // wishlist follows the account
  await page.goto(B + '/shop.html'); await page.waitForSelector('.product-card'); await page.locator('.product-card [data-wish]').first().click(); await page.waitForTimeout(800); const wl = await page.evaluate(async () => { const r = await fetch(API_BASE + '/customers/me/wishlist', { headers: { Authorization: 'Bearer ' + localStorage.getItem('cl_customer_token') } }); return r.json(); });
  ok('hearting a product while logged in saves it on the account', wl.ids.length === 1); await page.goto(B + '/account.html?tab=wishlist'); await page.waitForSelector('#wishGrid .product-card'); ok('Wishlist tab shows it with price and Add to cart', await page.locator('#wishGrid [data-quick]').count() === 1 && /₹/.test(await page.locator('#wishGrid').textContent())); await page.screenshot({ path: SHOTS + '/48-account-wishlist.png' }); await ctx.close();

  /* ================= ADMIN SCREENS ================= */
  const actx = await browser.newContext({ viewport: { width: 1440, height: 900 } }); await actx.route(BLOCK, (r) => r.abort()); await actx.addInitScript((t) => localStorage.setItem('cl_admin_token', t), owner);
  const a = await actx.newPage(); a.on('pageerror', (e) => errs.push('admin ' + a.url().split('/').pop() + ': ' + e.message)); a.on('dialog', (d) => d.accept()); const go = async (p) => { await a.goto(`${B}/admin/${p}`); await a.waitForTimeout(800); };
  await go('pincodes.html'); await a.fill('#csvText', 'pincode,city,state,serviceable,cod,eta\n700001,Kolkata,West Bengal,yes,yes,5\n380001,Ahmedabad,Gujarat,yes,no,4\n99999,bad,row,yes,yes,1\n'); await a.click('#importBtn'); await a.waitForSelector('#impOut:not(:empty)'); await a.waitForTimeout(700);
  ok('pincodes: CSV import adds rows and reports the bad one', /Imported 2 PIN codes/.test(await a.locator('#impOut').textContent()) && /99999/.test(await a.locator('#impOut').textContent()));
  await a.fill('#q', '7000'); await a.waitForTimeout(900); await a.locator('tr[data-pin="700001"] input[data-f=etaDays]').fill('9'); await a.locator('tr[data-pin="700001"] input[data-f=etaDays]').press('Tab'); await a.waitForTimeout(700);
  ok('pincodes: an inline edit saves', (await api('/admin/pincodes?q=700001', {}, owner)).body.pincodes[0].etaDays === 9);
  await a.locator('#modeToggle').evaluate((e) => e.click()); await a.waitForTimeout(800); ok('pincodes: the enforce-the-list switch is saved', (await api('/admin/pincodes', {}, owner)).body.mode === 'registry'); await a.screenshot({ path: SHOTS + '/49-admin-pincodes.png', fullPage: true }); await api('/admin/settings', { method: 'PUT', body: { pincodeCheckMode: 'off' } }, owner);
  await go('support.html'); ok('support: tickets listed with status tabs', await a.locator('#body tr').count() >= 2 && /New/.test(await a.locator('#tabs').textContent()));
  await a.locator('[data-open]').last().click(); await a.waitForSelector('#rSend'); await a.fill('#rText', 'Hello Gita — your parcel is out for delivery today.'); await a.click('#rSend'); await a.waitForTimeout(900); ok('support: replying moves the ticket to “waiting for customer”', (await api('/admin/support?q=gita', {}, owner)).body.tickets[0].status === 'WaitingCustomer'); await a.screenshot({ path: SHOTS + '/50-admin-support.png' });
  await a.selectOption('#rStatus', 'Resolved'); await a.waitForTimeout(800); ok('support: status can be set to Resolved', (await api('/admin/support?q=gita', {}, owner)).body.tickets[0].status === 'Resolved');
  await go('collections.html'); await a.waitForSelector('.method-card'); ok('collections: four carousels listed with real products', await a.locator('.method-card').count() === 4 && /Classic Row/.test(await a.locator('[data-key=featured]').textContent()));
  await a.locator('[data-key=featured] [data-f=title]').fill('Our Favourites'); await a.locator('[data-key=featured] [data-down]').first().click(); await a.locator('[data-key=featured] [data-save]').click(); await a.waitForTimeout(1000);
  const cols = (await api('/collections')).body.collections.find((c) => c.key === 'featured'); ok('collections: heading and order changes reach the storefront', cols.title === 'Our Favourites' && /Sculptural/.test(cols.products[0].name), cols.products.map((p) => p.name).join(', '));
  await go('settings.html'); await a.fill('[name=stockHoldMinutes]', '12'); await a.fill('[name=supportHours]', 'Mon–Sat 10 AM – 7 PM IST'); await a.click('#saveBtn'); await a.waitForTimeout(900); ok('settings: stock hold time and support hours save', (await api('/config/public')).body.supportHours === 'Mon–Sat 10 AM – 7 PM IST' && (await api('/admin/settings', {}, owner)).body.stockHoldMinutes === 12);
  const over = []; const mm = await browser.newContext({ viewport: { width: 390, height: 844 } }); await mm.route(BLOCK, (r) => r.abort()); await mm.addInitScript((t) => localStorage.setItem('cl_admin_token', t), owner); const mp = await mm.newPage(); for (const f of ['pincodes', 'support', 'collections']) { await mp.goto(`${B}/admin/${f}.html`); await mp.waitForTimeout(600); if (await mp.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)) over.push(f); } ok('new admin pages fit a phone screen', !over.length, over.join(','));
  const sp = await browser.newContext({ viewport: { width: 390, height: 844 } }); await sp.route(BLOCK, (r) => r.abort()); const sp1 = await sp.newPage(); const sover = []; for (const f of ['search.html?q=rack', 'help.html', 'index.html']) { await sp1.goto(`${B}/${f}`); await sp1.waitForTimeout(700); if (await sp1.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)) sover.push(f); } ok('search, help and home fit a phone screen', !sover.length, sover.join(','));
  console.log('\nJS errors:', errs.length ? '\n' + errs.join('\n') : 'none'); console.log(`${pass}/${pass + fail} passed`); await browser.close(); process.exit(fail ? 1 : 0);
})().catch((e) => { console.error('CRASH', e.message.slice(0, 500), (e.stack.match(/catalog\.ui\.js:\d+/) || [''])[0]); console.error('JS errors so far:', errs); process.exit(1); });
